collections:
  - name: ansible.posix
  - name: community.general
  - name: community.docker
  - name: community.mysql
    version: '2.1.0'
  - name: azure.azcollection
    version: '1.4.0'
  - name: community.crypto
    version: 1.6.2
  - name: community.kubernetes
