---

dist: jammy

language: python

python:
  - "3.10.5"

services:
  - docker

env:
  - ANSIBLE_INVENTORY_UNPARSED_WARNING=False ANSIBLE_LOCALHOST_WARNING=False

script:
  # YAML check
  - yamllint collections/ defaults/ handlers/ meta/ tasks/ tests/
  # Ansible Linter check
  - ansible-lint tests/kubelab.yml
  # Ansible syntax check
  - ansible-playbook tests/kubelab.yml
    --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
