---

- name: Create Cert Manager local folder
  ansible.builtin.file:
    path: "{{ k8s_local_workdir }}/cert-manager"
    state: directory
    mode: '0750'
  delegate_to: localhost

- name: Create Cert Manager namespace
  kubernetes.core.k8s:
    kubeconfig: "{{ k8s_kubeconfig }}"
    kind: Namespace
    name: "{{ k8s_cert_manager_namespace }}"
    state: present
  delegate_to: localhost

- name: Create Cert Manager resource files
  ansible.builtin.include_tasks: create-resource-from-template.yml
  with_items:
    # Cert Manager deployment
    - name: cert-manager/cert-manager-deployment
    # Cert Manager issuers
    - name: cert-manager/cert-manager-issuers
  delegate_to: localhost
