---

# Create resource yaml
- name: "Create yaml {{ item.name }}"
  ansible.builtin.template:
    src: "templates/{{ item.name }}.yaml.j2"
    dest: "{{ k8s_local_workdir }}/{{ item.name }}.yaml"
    mode: '0640'
  delegate_to: localhost

# Resource deployment
- name: "Create resource {{ item.name }}"
  kubernetes.core.k8s:
    kubeconfig: "{{ k8s_kubeconfig }}"
    state: present
    src: "{{ k8s_local_workdir }}/{{ item.name }}.yaml"
    wait: "{{ item.wait | default(true) }}"
    wait_timeout: "{{ item.timeout | default(k8s_wait_timeout) }}"
  delegate_to: localhost
