---

- name: Create Ingress NGINX local folder
  ansible.builtin.file:
    path: "{{ k8s_local_workdir }}/ingress-nginx"
    state: directory
    mode: '0750'
  delegate_to: localhost

- name: Create Ingress NGINX namespace
  kubernetes.core.k8s:
    kubeconfig: "{{ k8s_kubeconfig }}"
    kind: Namespace
    name: "{{ k8s_ingress_nginx_namespace }}"
    state: present
  delegate_to: localhost

- name: Create Ingress NGINX resource files
  ansible.builtin.include_tasks: create-resource-from-template.yml
  with_items:
    # Ingress NGINX deployment
    - name: ingress-nginx/ingress-nginx-deployment
      wait: false
    # Ingress NGINX services
    - name: ingress-nginx/ingress-nginx-services
