---

- name: Create MetalLB local folder
  ansible.builtin.file:
    path: "{{ k8s_local_workdir }}/metallb"
    state: directory
    mode: '0750'
  delegate_to: localhost

- name: Create MetalLB namespace
  kubernetes.core.k8s:
    kubeconfig: "{{ k8s_kubeconfig }}"
    kind: Namespace
    name: "{{ k8s_metallb_namespace }}"
    state: present
  delegate_to: localhost

- name: Fetch kube-proxy configMap in kube-system namespace
  kubernetes.core.k8s:
    kubeconfig: "{{ k8s_kubeconfig }}"
    kind: ConfigMap
    namespace: kube-system
    name: kube-proxy
  register: k8s_kube_proxy_configmap
  delegate_to: localhost

- name: Change strictARP parameter to true in the configMAP
  ansible.builtin.set_fact:
    k8s_kube_proxy_configmap_strictarp_true: "{{ (k8s_kube_proxy_configmap.result | replace('strictARP: false', 'strictARP: true')) }}"

- name: Apply the strictARP parameter to the existing configuration
  kubernetes.core.k8s:
    kubeconfig: "{{ k8s_kubeconfig }}"
    definition: "{{ k8s_kube_proxy_configmap_strictarp_true }}"
    state: present
  delegate_to: localhost

- name: Create MetalLB resources
  ansible.builtin.include_tasks: create-resource-from-template.yml
  with_items:
    # MetalLB deployment
    - name: metallb/metallb-deployment
    # MetalLB pools
    - name: metallb/metallb-pools
