---

- name: Get Kubernetes node status
  kubernetes.core.k8s_info:
    kubeconfig: "{{ k8s_kubeconfig }}"
    api_version: v1
    kind: Node
    label_selectors:
      - "kubernetes.io/hostname = {{ inventory_hostname }}"
  register: k8s_info
  changed_when: false
  failed_when: false
  delegate_to: localhost

- name: Set status of the node to NotReady
  ansible.builtin.set_fact:
    k8s_node_status: 'NotReady'

- name: Reset status of the node only if k8s_info is successful
  ansible.builtin.set_fact:
    k8s_node_status: "{{ lookup('vars', 'k8s_info') | community.general.json_query(jmespath_node_ready) | first }}"
  vars:
    jmespath_node_ready: "resources[0].status.conditions[?reason == 'KubeletReady'].type"
  when:
    - k8s_info.resources is defined
    - k8s_info.resources|length > 0
    - k8s_info.exception is undefined
