---

- name: "Add context {{ k8s_user.name }}@{{ k8s_cluster_name }} to {{ k8s_kubeconfig }}"
  local_action:
    module: ansible.builtin.blockinfile
    path: "{{ k8s_users_kubeconfig }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - context {{ k8s_user.name }}@{{ k8s_cluster_name }}"
    insertafter: "contexts:"
    block: |
      - context:
         cluster: {{ k8s_cluster_name }}
         namespace: {{ k8s_user.namespace }}
         user: {{ k8s_user.name }}
        name: {{ k8s_user.name }}@{{ k8s_cluster_name }}

- name: "Add user {{ k8s_user.name }} to {{ k8s_kubeconfig }}"
  local_action:
    module: ansible.builtin.blockinfile
    path: "{{ k8s_users_kubeconfig }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - user {{ k8s_user.name }}"
    insertafter: "users:"
    block: |
      - name: {{ k8s_user.name }}
        user:
          client-certificate: {{ k8s_user.name }}.crt
          client-key: {{ k8s_user.name }}.key
