---

- name: Restart docker
  ansible.builtin.service:
    name: docker
    state: restarted
    enabled: true
  become: true

- name: Restart containerd
  ansible.builtin.service:
    name: containerd
    state: restarted
    enabled: true
  become: true

- name: Restart firewalld
  ansible.builtin.service:
    name: firewalld
    state: restarted
    enabled: true
  become: true
