---

- name: restart docker daemon
  service:
    name: docker
    state: restarted
    enabled: yes
  become: true

- name: restart containerd daemon
  service:
    name: containerd
    state: restarted
    enabled: yes
  become: true
