---

- name: Create Ceph CSI local folder
  local_action:
    module: ansible.builtin.file
    path: "{{ k8s_local_workdir }}/ceph-csi"
    state: directory

- name: Create Ceph CSI namespace
  local_action:
    module: kubernetes.core.k8s
    kind: Namespace
    name: "{{ k8s_ceph_csi_namespace }}"
    state: present

- include_tasks: create-resource-from-template.yml
  with_items:
    # Ceph CSI RBD secret yaml
    - name: ceph-csi/ceph-csi-secret
    # Ceph CSI ConfigMap
    - name: ceph-csi/ceph-csi-config
    # Ceph CSI encryption KMS ConfigMap
    - name: ceph-csi/ceph-csi-encryption-kms-config
    # Ceph CSI RBAC provisioner
    - name: ceph-csi/ceph-csi-provisioner-rbac
    # Ceph CSI RBAC node plugin
    - name: ceph-csi/ceph-csi-nodeplugin-rbac
    # Ceph CSI RBD plugin provisioner deployment
    - name: ceph-csi/ceph-csi-rbdplugin-provisioner
    # Ceph CSI RBD plugin
    - name: ceph-csi/ceph-csi-rbdplugin
    # Ceph CSI StorageClass
    - name: ceph-csi/ceph-csi-storageclass
