---

- name: Create Cert Manager local folder
  local_action:
    module: ansible.builtin.file
    path: "{{ k8s_local_workdir }}/cert-manager"
    state: directory

- include_tasks: create-resource-from-template.yml
  with_items:
    # Cert Manager deployment
    - cert-manager/cert-manager-deployment
    # Cert Manager issuers
    - cert-manager/cert-manager-issuer
