---

- name: Create Cert Manager local folder
  local_action:
    module: ansible.builtin.file
    path: "{{ k8s_local_workdir }}/cert-manager"
    state: directory

- name: Create Cert Manager namespace
  local_action:
    module: kubernetes.core.k8s
    kubeconfig: "{{ k8s_kubeconfig }}"
    kind: Namespace
    name: "{{ k8s_cert_manager_namespace }}"
    state: present

- include_tasks: create-resource-from-template.yml
  with_items:
    # Cert Manager deployment
    - name: cert-manager/cert-manager-deployment
    # Cert Manager issuers
    - name: cert-manager/cert-manager-issuers
