---

- name: Checking active SWAP
  command: swapon -s
  register: active_swap
  changed_when: false

- name: Disabling SWAP since kubernetes can't work with swap enabled
  command: swapoff -a
  when:
    - active_swap.stdout != ""

- name: Disabling SWAP in fstab since kubernetes can't work with swap enabled
  replace:
    path: /etc/fstab
    regexp: '^([^#].* swap .*)$'
    replace: '#\1'

- name: "Build hosts file"
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].ansible_default_ipv4.address }} {{ item }}"
    state: present
  with_items: "{{ groups['k8s_nodes'] }}"

- name: Adding EPEL repo
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
  when:
    - k8s_epel_enable|bool

- name: Adding Docker-CE repo
  yum_repository:
    name: docker-ce
    description: Docker-CE
    baseurl: 'https://download.docker.com/linux/centos/7/$basearch/stable'
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: 'https://download.docker.com/linux/centos/gpg'

- name: Adding Kubernetes repo
  yum_repository:
    name: kubernetes
    description: Kubernetes
    baseurl: 'https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64'
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey:
      - 'https://packages.cloud.google.com/yum/doc/yum-key.gpg'
      - 'https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg'

- name: Installing required packages
  yum:
   name: "{{ k8s_packages }}"
   state: present

- name: Starting and Enabling the required services
  service:
   name: "{{ item }}"
   state: started
   enabled: yes
   masked: no
  with_items:
    - "{{ k8s_services }}"

- block:
    - name: Installing required packages
      yum:
       name: firewalld
       state: present

    - name: Starting and Enabling the firewalld service
      service:
       name: firewalld
       state: started
       enabled: yes
       masked: no

    - name: Allow master node network ports in Firewalld
      firewalld:
       port: "{{ item }}"
       state: enabled
       permanent: yes
       immediate: yes
      with_items:
        - "{{ k8s_master_ports }}"
      when:
        - k8s_role is defined
        - k8s_role == 'master'

    - name: Allow worker node network ports in Firewalld
      firewalld:
       port: "{{ item }}"
       state: enabled
       permanent: yes
       immediate: yes
      with_items:
        - "{{ k8s_worker_ports }}"
      when:
        - k8s_role is defined
        - k8s_role == 'worker'

    - name: Allow NodePort network ports in Firewalld
      firewalld:
       port: "{{ item }}"
       state: enabled
       permanent: yes
       immediate: yes
      with_items:
        - "{{ k8s_nodeport_ports }}"
      when:
        - k8s_role is defined
        - k8s_role == 'worker' or run_non_infra_pods|bool

    - name: Allow network addon ports
      firewalld:
       port: "{{ item }}"
       state: enabled
       permanent: yes
       immediate: yes
      with_items:
        - "{{ k8s_network_addon_ports }}"
      when:
        - k8s_role is defined

    - name: Enabling Bridge Firewall Rule
      sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: '1'
        sysctl_set: yes
        state: present
        reload: yes
  when:
    - k8s_firewalld_enable|bool
