---

- name: Deploy CSI RBD secret yaml
  template:
    src: "templates/csi-rbd-secret.yaml.j2"
    dest:  "kubernetes/csi-rbd-secret-{{ k8s_csi_ceph_id }}.yaml"
    owner: "{{ ansible_user }}"

- name: Check whether the secret is already defined
  command: kubectl get secret csi-rbd-secret -o jsonpath='{.metadata.name}'
  register: k8s_csi_rbd_secret
  changed_when: false
  failed_when: false

- name: Create the CSI RBD secret from yaml
  shell: |
    kubectl apply -f kubernetes/csi-rbd-secret-{{ k8s_csi_ceph_id }}.yaml
  when:
    - k8s_csi_rbd_secret.rc != 0
