---

- name: Get Ingress NGINX deployment yaml
  local_action:
    module: get_url
    url: "{{ k8s_ingress_nginx_url }}"
    dest: "{{ k8s_local_workdir }}/ingress-nginx.yaml"
    mode: '0664'

- name: Create Ingress NGINX deployment
  local_action:
    module: kubernetes.core.k8s
    kubeconfig: "{{ k8s_kubeconfig }}"
    state: present
    src: "{{ k8s_local_workdir }}/ingress-nginx.yaml"

- name: Deploy Ingress NGINX services yaml
  local_action:
    module: template
    src: "templates/ingress-nginx-services.yaml.j2"
    dest:  "{{ k8s_local_workdir }}/ingress-nginx-services.yaml"

- name: Create Ingress NGINX services resources
  local_action:
    module: kubernetes.core.k8s
    kubeconfig: "{{ k8s_kubeconfig }}"
    state: present
    src: "{{ k8s_local_workdir }}/ingress-nginx-services.yaml"
