---

- name: Create ingress-nginx local folder
  local_action:
    module: ansible.builtin.file
    path: "{{ k8s_local_workdir }}/ingress-nginx"
    state: directory

- include_tasks: create-resource-from-template.yml
  with_items:
    # Ingress NGINX deployment
    - name: ingress-nginx/ingress-nginx-deployment
      wait: false
    # Ingress NGINX services
    - name: ingress-nginx/ingress-nginx-services
