---

- import_tasks: common.yml
  become: true

- import_tasks: master.yml
  when:
    - k8s_role is defined
    - k8s_role == 'master'

- import_tasks: worker.yml
  when:
    - k8s_role is defined
    - k8s_role == 'worker'

- import_tasks: ceph-csi.yml
  when:
    - k8s_role is defined
    - k8s_role == 'master'
