---

- import_tasks: common.yml
  become: true

- import_tasks: master.yml
  when:
    - k8s_role is defined
    - k8s_role == 'master'

- import_tasks: worker.yml
  when:
    - k8s_role is defined
    - k8s_role == 'worker'

- include_tasks: users.yml
  with_items:
    - "{{ k8s_users }}"
  loop_control:
    loop_var: k8s_user
  when:
    - k8s_role is defined
    - k8s_role == 'master'
    - k8s_users is defined

- import_tasks: ceph-csi.yml
  when:
    - k8s_role is defined
    - k8s_role == 'master'
    - k8s_ceph_csi_enable|bool
