---

- name: Pulling images required for setting up a Kubernetes cluster
  command: kubeadm config images pull

- name: Resetting kubeadm
  command: kubeadm reset -f

- name: Initializing Kubernetes cluster
  command: kubeadm init --apiserver-advertise-address {{ hostvars[k8s_master_node]['ansible_default_ipv4']['address'] }} --pod-network-cidr={{ cidr_v }}

- name: Copying required files
  shell: |
   mkdir -p $HOME/.kube
   cp -f /etc/kubernetes/admin.conf $HOME/.kube/config
   chown $(id -u):$(id -g) $HOME/.kube/config

- name: Install Network Add-on
  command: "kubectl apply -f {{ k8s_network_addon }}"

- block:
    - name: Get taints for master node
      shell: |
        set -o pipefail
        kubectl describe node {{ ansible_hostname }} | \
        egrep '^Taints:.*node-role.kubernetes.io/master:NoSchedule'
      register: k8s_master_get_noschedule_taint
      changed_when: false
      failed_when: false

    - name: Enable master to run non infrastructure pods
      command: "kubectl taint nodes {{ ansible_hostname }} node-role.kubernetes.io/master:NoSchedule-"
      when:
        - k8s_master_get_noschedule_taint.rc == 0
  when:
    - run_non_infra_pods is defined
    - run_non_infra_pods|bool

- name: Get Token from Kubernetes
  shell: |
    set -o pipefail
    kubeadm token list | awk 'NR == 2 {print $1}'
  changed_when: false
  register: k8s_token_output
  delegate_to: "{{ k8s_master_node }}"

- name: Set fact token
  set_fact:
    k8s_token: "{{ k8s_token_output.stdout }}"
