---

- name: Resetting kubeadm
  command: kubeadm reset -f
  when:
    - k8s_reset|bool

- name: Get k8s cluster status
  command: kubectl cluster-info
  register: k8s_cluster_info
  changed_when: false
  failed_when: false

- block:
    - name: Pulling images required for setting up a Kubernetes cluster
      command: kubeadm config images pull

    - name: Initializing Kubernetes cluster
      command: kubeadm init --apiserver-advertise-address {{ hostvars[k8s_master_node]['ansible_default_ipv4']['address'] }} --pod-network-cidr={{ cidr_v }}

    - name: Create local .kube directory
      file:
        path: .kube
        state: directory

    - name: Copying required files
      copy:
        src: '/etc/kubernetes/admin.conf'
        dest:  '.kube/config'
        remote_src: yes

    - name: Install Network Add-on
      command: "kubectl apply -f {{ k8s_network_addon }}"
  when: k8s_cluster_info.rc != 0

- block:
    - name: Get taints for master node
      shell: |
        set -o pipefail
        kubectl describe node {{ ansible_hostname }} | \
        egrep '^Taints:.*node-role.kubernetes.io/master:NoSchedule'
      register: k8s_master_get_noschedule_taint
      changed_when: false
      failed_when: false

    - name: Enable master to run non infrastructure pods
      command: "kubectl taint nodes {{ ansible_hostname }} node-role.kubernetes.io/master:NoSchedule-"
      when:
        - k8s_master_get_noschedule_taint.rc == 0
  when:
    - run_non_infra_pods is defined
    - run_non_infra_pods|bool

- name: Get Token from Kubernetes
  shell: |
    set -o pipefail
    kubeadm token list | awk 'NR == 2 {print $1}'
  changed_when: false
  register: k8s_token_output
  delegate_to: "{{ k8s_master_node }}"

- name: Set fact token
  set_fact:
    k8s_token: "{{ k8s_token_output.stdout }}"
