---

- name: Fetch kube-proxy configMap in kube-system namespace
  local_action:
    module: kubernetes.core.k8s
    kubeconfig: "{{ k8s_kubeconfig }}"
    kind: ConfigMap
    namespace: kube-system
    name: kube-proxy
  register: k8s_kube_proxy_configmap

- name: Change strictARP parameter to true in the configMAP
  set_fact:
    k8s_kube_proxy_configmap_strictARP_true: "{{ (k8s_kube_proxy_configmap.result | replace('strictARP: false','strictARP: true')) }}"

- name: Apply the strictARP parameter to the existing configuration
  local_action:
    module: kubernetes.core.k8s
    kubeconfig: "{{ k8s_kubeconfig }}"
    definition: "{{ k8s_kube_proxy_configmap_strictARP_true }}"
    state: present

- name: Get MetalLB deployment yaml
  local_action:
    module: get_url
    url: "{{ k8s_metallb_url }}"
    dest: "{{ k8s_local_workdir }}/metallb.yaml"
    mode: '0664'

- name: Create MetalLB deployment
  local_action:
    module: kubernetes.core.k8s
    kubeconfig: "{{ k8s_kubeconfig }}"
    state: present
    src: "{{ k8s_local_workdir }}/metallb.yaml"
    wait: yes

- name: Deploy MetalLB pools yaml
  local_action:
    module: template
    src: "templates/metallb-pools.yaml.j2"
    dest:  "{{ k8s_local_workdir }}/metallb-pools.yaml"

- name: Create MetalLB pools resources
  local_action:
    module: kubernetes.core.k8s
    kubeconfig: "{{ k8s_kubeconfig }}"
    state: present
    src: "{{ k8s_local_workdir }}/metallb-pools.yaml"
