---

- name: Create MetalLB local folder
  local_action:
    module: ansible.builtin.file
    path: "{{ k8s_local_workdir }}/metallb"
    state: directory

- name: Fetch kube-proxy configMap in kube-system namespace
  local_action:
    module: kubernetes.core.k8s
    kubeconfig: "{{ k8s_kubeconfig }}"
    kind: ConfigMap
    namespace: kube-system
    name: kube-proxy
  register: k8s_kube_proxy_configmap

- name: Change strictARP parameter to true in the configMAP
  set_fact:
    k8s_kube_proxy_configmap_strictARP_true: "{{ (k8s_kube_proxy_configmap.result | replace('strictARP: false','strictARP: true')) }}"

- name: Apply the strictARP parameter to the existing configuration
  local_action:
    module: kubernetes.core.k8s
    kubeconfig: "{{ k8s_kubeconfig }}"
    definition: "{{ k8s_kube_proxy_configmap_strictARP_true }}"
    state: present

- include_tasks: create-resource-from-template.yml
  with_items:
    # MetalLB deployment
    - metallb/metallb-deployment
    # MetalLB pools
    - metallb/metallb-pools
