---

- name: Setting up other masters
  block:
    - name: "Check node join status"
      command: kubectl get nodes {{ ansible_fqdn }} -o jsonpath='{.status.conditions[?(@.reason == "KubeletReady")].type}'
      register: k8s_node_join_status
      changed_when: false
      failed_when: false
      delegate_to: "{{ k8s_master_node }}"

    - name: Joining control-plane nodes with kubernetes master
      command: |
        kubeadm join {{ k8s_balancer_VIP }}:{{ k8s_balancer_port }} \
        --token {{ hostvars[k8s_master_node]['k8s_token'] }} \
        --discovery-token-ca-cert-hash sha256:{{ hostvars[k8s_master_node]['k8s_discovery_token_ca_cert_hash'] }} \
        --control-plane \
        --certificate-key {{ k8s_cert_key }}
      when:
        - k8s_node_join_status.stdout != "Ready"
      become: true
  when: inventory_hostname != k8s_master_node
