---

- name: Create Users local folder
  local_action:
    module: ansible.builtin.file
    path: "{{ k8s_local_workdir }}/{{ item }}"
    state: directory
  with_items:
    - users
    - pki

- name: Copy remote /etc/kubernetes/pki certs on local directory
  fetch:
    src: '/etc/kubernetes/pki/{{ item }}'
    dest: "{{ k8s_local_workdir }}/pki/"
    flat: yes
  become: true
  with_items:
    - ca.crt
    - ca.key

- include_tasks: create-resource-from-template.yml
  with_items:
    # Users roles
    - name: users/users-roles
    # Users role bindings
    - name: users/users-rolebindings

- include_tasks: users-certificates.yml
  with_items:
    - "{{ k8s_users }}"
  loop_control:
    loop_var: k8s_user

- block:
    - name: Copy kubeconfig in local users dir
      local_action:
        module: ansible.builtin.copy
        src: "{{ k8s_local_workdir }}/admin.conf"
        dest: "{{ k8s_local_workdir }}/users/users.conf"

    - name: "Set k8s_users_kubeconfig fact to {{ k8s_local_workdir }}/users/users.conf"
      local_action:
        module: ansible.builtin.set_fact
        k8s_users_kubeconfig: "{{ k8s_local_workdir }}/users/users.conf"

    - include_tasks: users-kubeconfig.yml
      with_items:
        - "{{ k8s_users }}"
      loop_control:
        loop_var: k8s_user
  when:
    - k8s_force_users_kubeconfig_generation is defined
    - k8s_force_users_kubeconfig_generation|bool
