---

- name: Resetting Kubernetes worker node
  command: kubeadm reset -f
  when:
    - k8s_reset|bool
  become: true

- name: "Check node join status"
  command: kubectl get nodes {{ ansible_fqdn }} -o jsonpath='{.status.conditions[?(@.reason == "KubeletReady")].type}'
  register: k8s_node_join_status
  changed_when: false
  failed_when: false
  delegate_to: "{{ k8s_master_node }}"

- name: Joining worker nodes
  block:
  - name: Joining worker kubernetes single master
    command: kubeadm join --token {{ hostvars[k8s_master_node]['k8s_token'] }} \
      --discovery-token-ca-cert-hash sha256:{{ hostvars[k8s_master_node]['k8s_discovery_token_ca_cert_hash'] }} \
      {{ k8s_master_node }}:{{ k8s_master_port }}
    when: not k8s_multi_master

  - name: Joining worker kubernetes multi master
    command: |
      kubeadm join {{ k8s_balancer_VIP }}:{{ k8s_balancer_port }} \
      --token {{ hostvars[k8s_master_node]['k8s_token'] }} \
      --discovery-token-ca-cert-hash sha256:{{ hostvars[k8s_master_node]['k8s_discovery_token_ca_cert_hash'] }}
    when: k8s_multi_master
  when:
    - k8s_node_join_status.stdout != "Ready"
  become: true
