---

k8s_packages:
  - yum-utils
  - device-mapper-persistent-data
  - lvm2
  - vim
  - firewalld
  - docker
  - kubeadm
  - kubectl

k8s_services:
  - docker
  - kubelet
  - firewalld

k8s_ports:
  - "6443/tcp"
  - "10250/tcp"

k8s_network_addon: 'https://docs.projectcalico.org/v3.11/manifests/calico.yaml'
