---

k8s_epel_enable: true

k8s_packages:
  - yum-utils
  - device-mapper-persistent-data
  - lvm2
  - vim
  - docker-ce
  - kubeadm
  - kubectl

k8s_services:
  - docker
  - kubelet

k8s_master_ports:
  - 6443/tcp
  - 2379-2380/tcp
  - 10250/tcp
  - 10251/tcp
  - 10252/tcp

k8s_worker_ports:
  - 10250/tcp

k8s_nodeport_ports:
  - 30000-32767/tcp

k8s_firewalld_enable: true

k8s_network_cidr: 172.16.0.0/16
k8s_network_addon: calico
k8s_network_calico_ip_autodetection_method: 'interface=eth*'

k8s_network_addon_ports:
  - 179/tcp
  - 4789/udp
  - 5473/tcp
  - 4789/udp

k8s_dashboard_deploy: true
k8s_dashboard_url: https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-rc5/aio/deploy/recommended.yaml
k8s_dashboard_resources:
  - dashboard-admin-user_clusterrolebinding.yaml
  - dashboard-admin-user_serviceaccount.yaml

k8s_ceph_csi_enable: false
k8s_ceph_csi_release: master
k8s_ceph_csi_provisioner_rbac_url: https://raw.githubusercontent.com/ceph/ceph-csi/{{ k8s_ceph_csi_release }}/deploy/rbd/kubernetes/csi-provisioner-rbac.yaml
k8s_ceph_csi_nodeplugin_rbac_url: https://raw.githubusercontent.com/ceph/ceph-csi/{{ k8s_ceph_csi_release }}/deploy/rbd/kubernetes/csi-nodeplugin-rbac.yaml
k8s_ceph_csi_rbdplugin_provisioner_url: https://raw.githubusercontent.com/ceph/ceph-csi/{{ k8s_ceph_csi_release }}/deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml
k8s_ceph_csi_rbdplugin_url: https://raw.githubusercontent.com/ceph/ceph-csi/{{ k8s_ceph_csi_release }}/deploy/rbd/kubernetes/csi-rbdplugin.yaml

# Set this to true to force k8s cluster reset
k8s_reset: false
